package com.miaoshaproject.dataobject;

public class ShoppingCartDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.order_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_Id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_name
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.iterm_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Integer itermId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.iterm_title
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private String itermTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.iterm_price
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Double itermPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.iterm_num
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Integer itermNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.iterm_total
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    private Double itermTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.order_id
     *
     * @return the value of shopping_cart.order_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.order_id
     *
     * @param orderId the value for shopping_cart.order_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_Id
     *
     * @return the value of shopping_cart.user_Id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_Id
     *
     * @param userId the value for shopping_cart.user_Id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_name
     *
     * @return the value of shopping_cart.user_name
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_name
     *
     * @param userName the value for shopping_cart.user_name
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.iterm_id
     *
     * @return the value of shopping_cart.iterm_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Integer getItermId() {
        return itermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.iterm_id
     *
     * @param itermId the value for shopping_cart.iterm_id
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setItermId(Integer itermId) {
        this.itermId = itermId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.iterm_title
     *
     * @return the value of shopping_cart.iterm_title
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public String getItermTitle() {
        return itermTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.iterm_title
     *
     * @param itermTitle the value for shopping_cart.iterm_title
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setItermTitle(String itermTitle) {
        this.itermTitle = itermTitle == null ? null : itermTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.iterm_price
     *
     * @return the value of shopping_cart.iterm_price
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Double getItermPrice() {
        return itermPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.iterm_price
     *
     * @param itermPrice the value for shopping_cart.iterm_price
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setItermPrice(Double itermPrice) {
        this.itermPrice = itermPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.iterm_num
     *
     * @return the value of shopping_cart.iterm_num
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Integer getItermNum() {
        return itermNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.iterm_num
     *
     * @param itermNum the value for shopping_cart.iterm_num
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setItermNum(Integer itermNum) {
        this.itermNum = itermNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.iterm_total
     *
     * @return the value of shopping_cart.iterm_total
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public Double getItermTotal() {
        return itermTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.iterm_total
     *
     * @param itermTotal the value for shopping_cart.iterm_total
     *
     * @mbg.generated Mon Feb 03 15:40:47 CST 2020
     */
    public void setItermTotal(Double itermTotal) {
        this.itermTotal = itermTotal;
    }
}